### ISSUE TITLE
Unable to use as a library

### ISSUE THREAD

**Issue by andrewtbiehl** [stackmystack/grenadier#4]
I was unable use Grenadier as a library. I get an import error when referencing the package in a script.

The following self-contained GitHub Actions workflow is intended to demonstrate the issue. The workflow fails at the last step, when attempting to run the test script.

```yaml
name: Test Grenadier
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 2.3
      - name: Install Tree Sitter
        run: |
          git -C $HOME clone https://github.com/tree-sitter/tree-sitter.git
          cd $HOME/tree-sitter
          make
          sudo make install
      - name: Create Gemfile
        run: |
          cat << EOF > Gemfile
          source 'https://rubygems.org'
          gem 'tree_sitter', git: 'https://github.com/stackmystack/grenadier'
          EOF
      - name: Create test script
        run: |
          cat << EOF > test.rb
          require 'tree_sitter'
          puts TreeSitter::VERSION
          EOF
      - name: Install dependencies
        run: bundle install
      - name: Log relevant info
        run: |
          ruby --version
          bundler --version
          bundle list
          bundle env
          bundle info tree_sitter
      - name: Run test script
        run: ruby test.rb
```

Here is the error encountered in the last step:

```shell
<internal:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tree_sitter (LoadError)
    from <internal:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    from test.rb:1:in `<main>'
Error: Process completed with exit code 1.
```

In case it might be useful, here are the logs from the penultimate step:

<details>
<summary>Click to expand</summary>

````shell
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
Bundler version 2.3.18
Gems included by the bundle:
  * tree_sitter (0.20.6 d153b42)
Use `bundle info` to print more detailed information about a gem
## Environment

```
Bundler       2.3.18
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby
  Config Dir  /opt/hostedtoolcache/Ruby/3.1.2/x64/etc
RubyGems      3.3.7
  Gem Home    /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0
  Gem Path    /home/runner/.local/share/gem/ruby/3.1.0:/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0
  User Home   /home/runner
  User Path   /home/runner/.local/share/gem/ruby/3.1.0
  Bin Dir     /opt/hostedtoolcache/Ruby/3.1.2/x64/bin
Tools         
  Git         2.37.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-07-14
Git SHA           fc31b7f7d9
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'tree_sitter', git: 'https://github.com/stackmystack/grenadier'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/stackmystack/grenadier
  revision: d153b420a736f23d9f5ead258798e1f5917661f7
  specs:
    tree_sitter (0.20.6)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-linux

DEPENDENCIES
  tree_sitter!

BUNDLED WITH
   2.3.18
```
  * tree_sitter (0.20.6 d153b42)
    Summary: Ruby bindings for Tree-Sitter
    Homepage: https://www.github.com/stackmystack/grenadier
    Path: /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/bundler/gems/grenadier-d153b420a736
````

</details>

In my experience, replacing the references to Grenadier in the workflow with references to other Ruby libraries results in a successful run.

Thanks in advance for your help! :)
